/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/admin/bookings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Предстоящие встречи
         * @description Предстоящие встречи — единый список бронирований всех типов событий.
         *
         *     Возвращаются только брони, которые ещё не начались (`start >= now`),
         *     отсортированные по `start` по возрастанию.
         */
        get: operations["Admin_listUpcomingBookings"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/event-types": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Список типов событий
         * @description Список типов событий владельца, отсортированный по `createdAt`
         *     по возрастанию.
         */
        get: operations["Admin_listEventTypes"];
        put?: never;
        /**
         * Создать тип события
         * @description Создать тип события.
         *
         *     Идентификатор задаёт владелец. Если тип события с таким `id` уже есть,
         *     возвращается `409 EVENT_TYPE_ALREADY_EXISTS` — существующий тип не
         *     перезаписывается.
         *
         *     Длительность не влияет на уже созданные бронирования: они хранят свою
         *     длительность на момент записи.
         */
        post: operations["Admin_createEventType"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Профиль владельца календаря
         * @description Профиль владельца календаря.
         *
         *     Возвращает настройки, по которым строится сетка слотов: рабочие часы,
         *     шаг сетки и глубину окна записи. Профиль всегда существует.
         */
        get: operations["Admin_getProfile"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/bookings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Создать бронирование
         * @description Создать бронирование на выбранный слот.
         *
         *     Сервер проверяет по порядку:
         *
         *     - `eventTypeId` существует, иначе `404 EVENT_TYPE_NOT_FOUND`;
         *     - `start` выровнен по шагу сетки, иначе `422 SLOT_NOT_ALIGNED`;
         *     - интервал `[start, start + durationMinutes)` целиком лежит в окне записи `[now, now + 14 дней]`, иначе `422 SLOT_OUT_OF_WINDOW`;
         *     - интервал целиком помещается в рабочие часы одного дня, иначе `422 SLOT_OUTSIDE_WORKING_HOURS`;
         *     - интервал не пересекается ни с одним существующим бронированием любого типа события, иначе `409 SLOT_ALREADY_BOOKED`.
         *
         *     Проверка занятости и запись выполняются атомарно: при гонке двух гостей
         *     за один слот успешным будет ровно один запрос.
         */
        post: operations["Public_createBooking"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/event-types": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Список видов брони
         * @description Виды брони, доступные гостю.
         *
         *     Отдаёт название, описание и длительность каждого типа события —
         *     данные для страницы выбора.
         */
        get: operations["Public_listEventTypes"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/event-types/{eventTypeId}/slots": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Свободные слоты типа события
         * @description Свободные слоты выбранного типа события на ближайшие 14 суток.
         *
         *     Сетка строится так:
         *
         *     1. Берутся сутки от текущего момента до `now + 14 дней`.
         *     2. Внутри рабочих часов владельца расставляются точки старта с шагом `slotStepMinutes` (30 минут).
         *     3. Остаются только те точки, для которых интервал `[start, start + durationMinutes)` целиком помещается в рабочие часы того же дня и целиком попадает в окно записи.
         *     4. Отбрасываются точки в прошлом и те, чей интервал пересекается с любым существующим бронированием — независимо от его типа события.
         *
         *     Ответ отражает состояние на момент запроса: слот может быть занят
         *     другим гостем до отправки формы, поэтому источником истины остаётся
         *     `POST /api/bookings`.
         */
        get: operations["Public_listSlots"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description Подтверждённое бронирование слота гостем. */
        Booking: {
            /** @description Идентификатор брони, выданный сервером. */
            id: components["schemas"]["BookingId"];
            /** @description Тип события, на который записался гость. */
            eventTypeId: components["schemas"]["EventTypeId"];
            /** @description Название типа события на момент чтения — чтобы не делать второй запрос. */
            eventTypeTitle: string;
            /**
             * Format: date-time
             * @description Начало встречи, UTC.
             */
            start: string;
            /**
             * Format: date-time
             * @description Конец встречи, UTC. Вычисляется как `start + durationMinutes`.
             */
            end: string;
            /**
             * Format: int32
             * @description Длительность встречи в минутах, зафиксированная при бронировании.
             */
            durationMinutes: number;
            /** @description Контактные данные гостя. */
            guest: components["schemas"]["Guest"];
            /**
             * Format: date-time
             * @description Момент создания брони, UTC.
             */
            createdAt: string;
        };
        /**
         * @description Запрос на создание брони. Гость передаёт только начало встречи —
         *     конец сервер вычисляет сам из длительности типа события.
         */
        BookingCreate: {
            /** @description Выбранный тип события. */
            eventTypeId: components["schemas"]["EventTypeId"];
            /**
             * Format: date-time
             * @description Начало выбранного слота, UTC. Должно совпадать со слотом из `SlotsPage`.
             */
            start: string;
            /** @description Контактные данные гостя. */
            guest: components["schemas"]["Guest"];
        };
        /**
         * Format: uuid
         * @description Идентификатор бронирования. Генерируется сервером (UUID v4).
         */
        BookingId: string;
        /** @description Список бронирований для админской части. */
        BookingList: {
            /** @description Бронирования всех типов событий в одном списке, отсортированы по `start`. */
            items: components["schemas"]["Booking"][];
        };
        /** @description Окно записи, внутри которого действителен список слотов. */
        BookingWindow: {
            /**
             * Format: date-time
             * @description Начало окна, UTC. Момент выполнения запроса.
             */
            from: string;
            /**
             * Format: date-time
             * @description Конец окна, UTC. Ровно `from + 14 суток`.
             */
            to: string;
        };
        /**
         * Format: email
         * @description Адрес электронной почты.
         */
        Email: string;
        /** @description Единый формат тела ошибки для всех эндпоинтов. */
        ErrorBody: {
            /** @description Машиночитаемый код ошибки. */
            code: components["schemas"]["ErrorCode"];
            /** @description Человекочитаемое описание для отображения пользователю. */
            message: string;
            /**
             * @description Дополнительный контекст ошибки.
             *     Например, для `SLOT_ALREADY_BOOKED` — занятый интервал,
             *     для `VALIDATION_FAILED` — список полей с проблемами.
             */
            details?: Record<string, never>;
        };
        /** @description Машиночитаемый код ошибки. Клиент принимает решения по `code`, не по тексту. */
        ErrorCode: ("BAD_REQUEST" | "EVENT_TYPE_NOT_FOUND" | "EVENT_TYPE_ALREADY_EXISTS" | "SLOT_ALREADY_BOOKED" | "SLOT_OUT_OF_WINDOW" | "SLOT_NOT_ALIGNED" | "SLOT_OUTSIDE_WORKING_HOURS" | "VALIDATION_FAILED") | string;
        /** @description Тип события (вид брони), который владелец предлагает гостям. */
        EventType: {
            /**
             * @description Идентификатор, заданный владельцем при создании.
             * @example intro-call
             */
            id: components["schemas"]["EventTypeId"];
            /**
             * @description Название, которое видит гость.
             * @example Знакомство
             */
            title: string;
            /**
             * @description Описание встречи: о чём она и как проходит.
             * @example Короткий созвон, чтобы обсудить задачу и понять, чем я могу помочь.
             */
            description: string;
            /**
             * Format: int32
             * @description Длительность встречи в минутах. Определяет длину интервала `[start, end)`
             *     и то, какие слоты сетки помещаются в рабочие часы.
             * @example 30
             */
            durationMinutes: number;
            /**
             * Format: date-time
             * @description Момент создания типа события, UTC.
             */
            createdAt: string;
        };
        /** @description Данные для создания типа события. Идентификатор задаёт владелец. */
        EventTypeCreate: {
            /** @description Уникальный идентификатор типа события. */
            id: components["schemas"]["EventTypeId"];
            title: string;
            description: string;
            /** Format: int32 */
            durationMinutes: number;
        };
        /**
         * @description Идентификатор типа события. Задаётся владельцем календаря вручную,
         *     читаемый slug в нижнем регистре, участвует в публичных ссылках.
         */
        EventTypeId: string;
        /** @description Список типов событий. */
        EventTypeList: {
            items: components["schemas"]["EventType"][];
        };
        /** @description Контактные данные гостя. Аккаунт не создаётся, данные живут внутри брони. */
        Guest: {
            /**
             * @description Имя гостя.
             * @example Игорь Петров
             */
            name: string;
            /** @description E-mail гостя для подтверждения встречи. */
            email: components["schemas"]["Email"];
            /** @description Необязательный комментарий: тема встречи, вопросы, ссылки. */
            note?: string;
        };
        /**
         * @description Владелец календаря — единственный заранее заданный профиль системы.
         *     Не создаётся и не удаляётся через API, доступен только для чтения.
         */
        Owner: {
            /**
             * @description Стабильный идентификатор профиля.
             * @example owner
             */
            id: string;
            /**
             * @description Отображаемое имя владельца на публичных страницах.
             * @example Анна Смирнова
             */
            name: string;
            /** @description Контактный e-mail владельца. */
            email: components["schemas"]["Email"];
            /**
             * @description Часовой пояс расписания. В текущей версии всегда `UTC`.
             * @example UTC
             * @enum {string}
             */
            timeZone: "UTC";
            /** @description Рабочие часы, внутри которых строится сетка слотов. */
            workingHours: components["schemas"]["WorkingHours"];
            /**
             * Format: int32
             * @description Шаг сетки слотов в минутах. В текущей версии всегда 30.
             * @example 30
             */
            slotStepMinutes: number;
            /**
             * Format: int32
             * @description Глубина окна записи в сутках от текущего момента. В текущей версии всегда 14.
             * @example 14
             */
            bookingWindowDays: number;
        };
        /** @description Публичная карточка типа события: всё, что нужно гостю для выбора. */
        PublicEventType: {
            id: components["schemas"]["EventTypeId"];
            title: string;
            description: string;
            /** Format: int32 */
            durationMinutes: number;
        };
        /** @description Публичный список типов событий. */
        PublicEventTypeList: {
            items: components["schemas"]["PublicEventType"][];
        };
        /**
         * @description Слот — вычисляемый интервал-кандидат для встречи. Отдельно не хранится:
         *     сетка строится на лету из рабочих часов владельца, шага сетки и длительности
         *     выбранного типа события, а затем из неё вычитаются занятые интервалы.
         */
        Slot: {
            /**
             * Format: date-time
             * @description Начало слота, UTC. Всегда выровнено по шагу сетки.
             * @example 2026-08-17T09:30:00Z
             */
            start: string;
            /**
             * Format: date-time
             * @description Конец слота, UTC. Равен `start + durationMinutes` выбранного типа события.
             * @example 2026-08-17T10:00:00Z
             */
            end: string;
        };
        /** @description Ответ со свободными слотами для конкретного типа события. */
        SlotsPage: {
            /** @description Тип события, для которого построена сетка. */
            eventTypeId: components["schemas"]["EventTypeId"];
            /**
             * Format: int32
             * @description Длительность встречи, использованная при построении сетки.
             */
            durationMinutes: number;
            /**
             * @description Часовой пояс возвращаемых значений времени.
             * @enum {string}
             */
            timeZone: "UTC";
            /** @description Границы окна записи. */
            window: components["schemas"]["BookingWindow"];
            /**
             * @description Только свободные слоты, отсортированные по `start` по возрастанию.
             *     Занятые интервалы в ответ не попадают. Пустой массив — записаться некуда.
             */
            slots: components["schemas"]["Slot"][];
        };
        /** @description Время суток в формате `HH:mm` (UTC). */
        TimeOfDay: string;
        /**
         * @description Рабочие часы владельца календаря в UTC.
         *     Слоты формируются только внутри этого промежутка, `end` строго больше `start`.
         */
        WorkingHours: {
            /**
             * @description Начало рабочего дня, UTC.
             * @example 09:00
             */
            start: components["schemas"]["TimeOfDay"];
            /**
             * @description Конец рабочего дня, UTC. Встреча должна завершиться не позже него.
             * @example 18:00
             */
            end: components["schemas"]["TimeOfDay"];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    Admin_listUpcomingBookings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BookingList"];
                };
            };
        };
    };
    Admin_listEventTypes: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "items": [
                     *         {
                     *           "id": "intro-call",
                     *           "title": "Знакомство",
                     *           "description": "Короткий созвон, чтобы обсудить задачу и понять, чем я могу помочь.",
                     *           "durationMinutes": 30,
                     *           "createdAt": "2026-08-01T07:12:44Z"
                     *         },
                     *         {
                     *           "id": "deep-dive",
                     *           "title": "Разбор задачи",
                     *           "description": "Час на детальный разбор с демонстрацией экрана и правками по ходу.",
                     *           "durationMinutes": 60,
                     *           "createdAt": "2026-08-03T15:40:09Z"
                     *         },
                     *         {
                     *           "id": "quick-sync",
                     *           "title": "Быстрая синхронизация",
                     *           "description": "Пятнадцать минут на один конкретный вопрос без подготовки.",
                     *           "durationMinutes": 15,
                     *           "createdAt": "2026-08-11T06:55:20Z"
                     *         }
                     *       ]
                     *     }
                     */
                    "application/json": components["schemas"]["EventTypeList"];
                };
            };
        };
    };
    Admin_createEventType: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                /**
                 * @example {
                 *       "id": "quick-sync",
                 *       "title": "Быстрая синхронизация",
                 *       "description": "Пятнадцать минут на один конкретный вопрос без подготовки.",
                 *       "durationMinutes": 15
                 *     }
                 */
                "application/json": components["schemas"]["EventTypeCreate"];
            };
        };
        responses: {
            /** @description The request has succeeded and a new resource has been created as a result. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "id": "quick-sync",
                     *       "title": "Быстрая синхронизация",
                     *       "description": "Пятнадцать минут на один конкретный вопрос без подготовки.",
                     *       "durationMinutes": 15,
                     *       "createdAt": "2026-08-11T06:55:20Z"
                     *     }
                     */
                    "application/json": components["schemas"]["EventType"];
                };
            };
            /** @description Некорректный запрос: не разобрано тело, неверный формат даты и т. п. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Конфликт состояния: слот уже занят или идентификатор типа события занят. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Запрос синтаксически корректен, но нарушает доменные правила. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    Admin_getProfile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "id": "owner",
                     *       "name": "Анна Смирнова",
                     *       "email": "anna@meetly.local",
                     *       "timeZone": "UTC",
                     *       "workingHours": {
                     *         "start": "09:00",
                     *         "end": "18:00"
                     *       },
                     *       "slotStepMinutes": 30,
                     *       "bookingWindowDays": 14
                     *     }
                     */
                    "application/json": components["schemas"]["Owner"];
                };
            };
        };
    };
    Public_createBooking: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BookingCreate"];
            };
        };
        responses: {
            /** @description The request has succeeded and a new resource has been created as a result. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Booking"];
                };
            };
            /** @description Некорректный запрос: не разобрано тело, неверный формат даты и т. п. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Запрошенный ресурс не найден. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Конфликт состояния: слот уже занят или идентификатор типа события занят. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Запрос синтаксически корректен, но нарушает доменные правила. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    Public_listEventTypes: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicEventTypeList"];
                };
            };
        };
    };
    Public_listSlots: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Идентификатор типа события. */
                eventTypeId: components["schemas"]["EventTypeId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SlotsPage"];
                };
            };
            /** @description Некорректный запрос: не разобрано тело, неверный формат даты и т. п. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Запрошенный ресурс не найден. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
}
